#!/bin/bash
pushd ~
if [ -f /etc/lsb-release ]; then
    echo
else
    echo -e "\033[44m 非ubuntu系统 停止运行! \033[44m";
    exit 0
fi
#检测是否为root用户
if [[ $EUID != 0 ]];then
    echo -e "\033[44m 非root用户 请登录root用户后使用该脚本 \033[44m";
    exit 0
else
    sleep 1s
fi
#检测curl安装状态
if ! [ -x "$(command -v curl)" ]; then
    echo -e "\033[44m 未检测到未安装curl  \033[44m";
    apt update
    apt install curl -y
fi
#检测wget安装状态
if ! [ -x "$(command -v wget)" ]; then
    echo -e "\033[44m 未检测到未安装wget 开始安装 \033[44m";
    apt update
    apt install wget -y
fi
#检测whiptail安装状态
if ! [ -x "$(command -v whiptail)" ]; then
    echo -e "\033[44m 未检测到未安装whiptail 开始安装 \033[44m";
    apt update
    apt install whiptail -y
fi
#脚本本地化
if [ -f /usr/bin/bhyz ]; then
     echo -e "\033[44m 文件存在 执行更新 \033[44m"
     echo
     version=`curl -s https://gitee.com/baihu433/Ubuntu-Yunzai/raw/version`
    if [ "$version" != "bhyz1.0" ]; then
        rm -rf /usr/bin/bhyz
        wget https://gitee.com/baihu433/Ubuntu-Yunzai/raw/bhyz
        mv bhyz /usr/bin/bhyz
        chmod +x /usr/bin/bhyz
        rm -rf  wget-log
    else
        echo
        echo -e "\033[44m 已是最新 \033[44m"
    fi
else
    echo -e "\033[44m 文件不存在 开始下载 \033[44m"
    echo 
    wget https://gitee.com/baihu433/Ubuntu-Yunzai/raw/bhyz
    mv bhyz /usr/bin/bhyz
    chmod +x /usr/bin/bhyz
    rm -rf wget-log
fi
#作者信息？？？
whiptail --title "Test Message Box" --msgbox "
注意：脚本完全免费，禁止倒卖
此脚本作者为白狐
[QQ:1522099983[Q群:914418311]
项目地址:
https://gitee.com/baihu433/termux-Yunzai

回车继续安装 ctrl+c退出" 15 60 